# Beacon Chain Configuration
PRESET_BASE: 'mainnet'
CONFIG_NAME: 'private-network'

# Genesis
GENESIS_FORK_VERSION: 0x10000001
GENESIS_DELAY: 0

# Time parameters
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32
MIN_GENESIS_TIME: 0
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1

# Deposit contract
DEPOSIT_CHAIN_ID: 1337
DEPOSIT_NETWORK_ID: 1337
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x10000002

# Bellatrix (Merge)
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x10000003

# Capella (Shanghai)
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x10000004

# Deneb (Cancun)
DENEB_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x10000005

# Terminal total difficulty
TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0
